service: mic-user-manage

frameworkVersion: '3'

plugins:
  - serverless-localstack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: us-east-2
  memorySize: 256
  timeout: 30 
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            - 'secretsmanager:ListSecretVersionIds'
          Resource: 
            - ${ssm:SECRETSMANAGER_RDS_ARN}
  environment:
    prefixApp: MIC-USER-MANAGE
    STAGE: ${self:provider.stage}
    SECRET_RDS: ${ssm(raw):/aws/reference/secretsmanager/user/prod/mysql}
  vpc:
    securityGroupIds:
    - ${ssm:DB_CONFIG_SECURITY_GROUP_ID}
    subnetIds:
    - ${ssm:DB_CONFIG_SUBNET1_ID}
    - ${ssm:DB_CONFIG_SUBNET2_ID}
    - ${ssm:DB_CONFIG_SUBNET3_ID}

custom:
  funcDir: src/functions
  webpackIncludeModules:
    forceInclude:
      - mysql
      - mysql2
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost  
    edgePort: 4566 
    autostart: false  
    lambda:
      mountCode: True
    docker:
      sudo: True

functions:
  ${file(${self:custom.funcDir}/user/_handlers.yml)}

          

    